#!/usr/bin/Rscript

.Last <- function() {
  try(mongo.destroy(mongo), silent = TRUE)
}
library(rmongodb, quietly = TRUE)
library(cnn.stories)
import::from("plyr", "dlply", "ldply")

mongo      <- mongoConnect()
ns         <- paste(Sys.getenv("MONGO_CNN_DB"), Sys.getenv("MONGO_CNN_COLLECTION"), sep = ".")
stories    <- mongo.find.all(mongo, ns, fields = list("_id" = FALSE, url = TRUE))

master <- ldply(SOURCES, scrapeStories)
master <- master[ paste0(CNN, master$href) %nin% unlist(stories, use.names = FALSE), ]
cat(paste(nrow(master), "new articles have been collected from CNN at", Sys.time(), "Scraping now...\n"))

if (nrow(master) > 0) {
  articles  <- dlply(master, "href", scrapeArticle)
  articles  <- parseLocations(articles)
  articles  <- distributeTopics(articles, mongo)
  bson_list <- lapply(articles, mongo.bson.from.list)
  mongo.insert.batch(mongo, ns, bson_list)
  cat("Scraping complete and stored.\n")
}
invisible( mongo.destroy(mongo) )
