#!/usr/local/bin/Rscript

source("scraper.R")

if ( Sys.getenv("CNN_STORAGE") == "REMOTE") {
library(RMySQL);
db <- dbConnect(MySQL(),
                 user     = Sys.getenv("MYSQL_CNN_USER"),
                 password = Sys.getenv("MYSQL_CNN_PASSWORD"),
                 host     = Sys.getenv("MYSQL_CNN_HOST"),
                 port     = Sys.getenv("MYSQL_CNN_PORT") %>% as.numeric(),
                 dbname   = "CNN_Article_Archive")
sql_select <- 
"SELECT Title, href, Source FROM Articles 
WHERE STR_TO_DATE(`Last.scene.date`, '%Y-%m-%d') > CURDATE() - INTERVAL 3 DAY"

recent_stories <- dbGetQuery(db, sql_select)
new_stories <- anti_join(master, recent_stories, c("Title", "href", "Source"))
print(paste(nrow(new_stories), "new articles have been scraped from CNN at", lubridate::now()))
dbWriteTable(conn = db, name = "Articles", value = new_stories, row.names = FALSE, append = TRUE) %>% invisible()

} else {
original <-   read.csv("data/articles.csv", stringsAsFactors = FALSE) %>% 
  mutate(Last.scene.date = as.POSIXct(Last.scene.date, tz = "UTC"));

new_master <- rbind(original, master) %>% 
  arrange(desc(Last.scene.date))

repeated_stories <- new_master %>% select(-Last.scene.date) %>% duplicated()

print(paste(nrow(master) - sum(repeated_stories), 
            "new articles have been scraped from CNN at", lubridate::now()))
write.csv(new_master[!repeated_stories, ], "data/articles.csv", row.names = FALSE)
}
